In [1]:
import pandas as pd
import numpy as np

df1 = pd.read_csv("../data/processed/dataset1_clean.csv")
season = pd.read_csv("../data/processed/dataset2_season_lookup.csv")

print(df1.shape)
print(season.shape)
print(df1.columns.tolist())
print(season.columns.tolist())import pandas as pd
import numpy as np

df1 = pd.read_csv("../data/raw/ICRISAT + IMD weather.csv")
print(df1.shape)
df1.info()
df1.describe(include='all')

(50765, 20)
<class 'pandas.DataFrame'>
RangeIndex: 50765 entries, 0 to 50764
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Dist Code                  50765 non-null  int64
 1   Year                       50765 non-null  int64
 2   State Code                 50765 non-null  int64
 3   State Name                 50765 non-null  str
 4   Dist Name                  50765 non-null  str
 5   Crop                       50765 non-null  str
 6   Area_ha                    50765 non-null  float64
 7   Yield_kg_per_ha            50765 non-null  float64
 8   N_req_kg_per_ha            50765 non-null  float64
 9   P_req_kg_per_ha            50765 non-null  float64
 10  K_req_kg_per_ha            50765 non-null  float64
 11  Total_N_kg                 50765 non-null  float64
 12  Total_P_kg                 50765 non-null  float64
 13  Total_K_kg                 50765 non-null  float64
 14  Temperature_C              50765 non-null  int64
 15  Humidity_%                 50765 non-null  int64
 16  pH                         50765 non-null  float64
 17  Rainfall_mm                50765 non-null  int64
 18  Wind_Speed_m_s             50765 non-null  float64
 19  Solar_Radiation_MJ_m2_day  50765 non-null  int64
dtypes: float64(10), int64(7), str(3)
memory usage: 7.7 MB

,Dist Code,Year,State Code,State Name,Dist Name,Crop,Area_ha,Yield_kg_per_ha,N_req_kg_per_ha,P_req_kg_per_ha,K_req_kg_per_ha,Total_N_kg,Total_P_kg,Total_K_kg,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day
count,50765.000000,50765.000000,50765.000000,50765,50765,50765,5.076500e+04,50765.000000,50765.000000,50765.000000,50765.000000,5.076500e+04,5.076500e+04,5.076500e+04,50765.000000,50765.000000,50765.000000,50765.000000,50765.000000,50765.000000
unique,NaN,NaN,NaN,20,311,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,Uttar Pradesh,Chhindwara,rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,7488,208,14978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,250.218753,1991.562770,9.169822,NaN,NaN,NaN,6.376523e+04,1159.814711,28.567342,13.517313,22.676814,2.263186e+06,1.080920e+06,1.933931e+06,23.261972,69.454151,6.283906,848.092190,2.156574,18.626298
std,269.062837,14.936844,4.852093,NaN,NaN,NaN,1.127902e+05,1005.066007,26.289891,12.036834,19.432244,5.322257e+06,2.546764e+06,4.640902e+06,2.772772,7.767090,0.247693,239.465123,0.516744,2.066976
min,1.000000,1966.000000,1.000000,NaN,NaN,NaN,1.000000e+01,0.280000,0.007560,0.003360,0.007560,9.180000e+00,4.080000e+00,9.180000e+00,20.000000,60.000000,6.000000,600.000000,1.500000,16.000000
25%,72.000000,1979.000000,6.000000,NaN,NaN,NaN,2.340000e+03,500.000000,10.447020,5.361200,9.720920,3.592870e+04,1.704094e+04,3.023970e+04,20.000000,60.000000,6.000000,600.000000,1.500000,16.000000
50%,144.000000,1992.000000,9.000000,NaN,NaN,NaN,1.690000e+04,922.080000,20.291310,10.030700,17.000000,2.880000e+05,1.400001e+05,2.419987e+05,22.000000,70.000000,6.500000,800.000000,2.000000,18.000000
75%,230.000000,2004.000000,12.000000,NaN,NaN,NaN,6.890000e+04,1533.600000,39.574710,18.188640,29.662820,1.692500e+06,8.081441e+05,1.378628e+06,25.000000,80.000000,6.500000,1200.000000,2.500000,20.000000
max,917.000000,2017.000000,20.000000,NaN,NaN,NaN,1.154230e+06,58363.640000,1050.545520,583.636400,1050.545520,8.037524e+07,3.858011e+07,7.073021e+07,28.000000,80.000000,6.500000,1200.000000,3.000000,22.000000

In [2]:
print("Duplicate rows:", df1.duplicated().sum())
print("\nNull counts:\n", df1.isnull().sum())
print("\nUnique crops:", df1['Crop'].unique())
print("\nUnique states:", df1['State Name'].nunique())
print("\nYear range:", df1['Year'].min(), "-", df1['Year'].max())

Duplicate rows: 0

Null counts:
 Dist Code                    0
Year                         0
State Code                   0
State Name                   0
Dist Name                    0
Crop                         0
Area_ha                      0
Yield_kg_per_ha              0
N_req_kg_per_ha              0
P_req_kg_per_ha              0
K_req_kg_per_ha              0
Total_N_kg                   0
Total_P_kg                   0
Total_K_kg                   0
Temperature_C                0
Humidity_%                   0
pH                           0
Rainfall_mm                  0
Wind_Speed_m_s               0
Solar_Radiation_MJ_m2_day    0
dtype: int64

Unique crops: <StringArray>
['rice', 'maize', 'chickpea', 'cotton']
Length: 4, dtype: str

Unique states: 20

Year range: 1966 - 2017

In [3]:
print(df1[['Area_ha','Yield_kg_per_ha','Temperature_C','Humidity_%','pH','Rainfall_mm','Wind_Speed_m_s','Solar_Radiation_MJ_m2_day']].describe())

            Area_ha  Yield_kg_per_ha  Temperature_C    Humidity_%  \
count  5.076500e+04     50765.000000   50765.000000  50765.000000
mean   6.376523e+04      1159.814711      23.261972     69.454151
std    1.127902e+05      1005.066007       2.772772      7.767090
min    1.000000e+01         0.280000      20.000000     60.000000
25%    2.340000e+03       500.000000      20.000000     60.000000
50%    1.690000e+04       922.080000      22.000000     70.000000
75%    6.890000e+04      1533.600000      25.000000     80.000000
max    1.154230e+06     58363.640000      28.000000     80.000000

                 pH   Rainfall_mm  Wind_Speed_m_s  Solar_Radiation_MJ_m2_day
count  50765.000000  50765.000000    50765.000000               50765.000000
mean       6.283906    848.092190        2.156574                  18.626298
std        0.247693    239.465123        0.516744                   2.066976
min        6.000000    600.000000        1.500000                  16.000000
25%        6.000000    600.000000        1.500000                  16.000000
50%        6.500000    800.000000        2.000000                  18.000000
75%        6.500000   1200.000000        2.500000                  20.000000
max        6.500000   1200.000000        3.000000                  22.000000

In [4]:
print("Unique temperature values:", sorted(df1['Temperature_C'].unique()))
print("Unique humidity values:", sorted(df1['Humidity_%'].unique()))
print("Unique pH values:", sorted(df1['pH'].unique()))
print("Unique rainfall values:", sorted(df1['Rainfall_mm'].unique()))

Unique temperature values: [np.int64(20), np.int64(22), np.int64(25), np.int64(28)]
Unique humidity values: [np.int64(60), np.int64(65), np.int64(70), np.int64(80)]
Unique pH values: [np.float64(6.0), np.float64(6.5)]
Unique rainfall values: [np.int64(600), np.int64(700), np.int64(800), np.int64(1200)]

In [5]:
print(df1.nlargest(10, 'Yield_kg_per_ha')[['Crop','State Name','Year','Yield_kg_per_ha']])

           Crop      State Name  Year  Yield_kg_per_ha
48486  chickpea           Bihar  2007         58363.64
48786  chickpea           Bihar  2007         32000.00
31641     maize         Haryana  2016         21428.57
9198      maize  Andhra Pradesh  2017         11368.52
8368      maize  Andhra Pradesh  2010         11120.22
8396      maize  Andhra Pradesh  2017         10163.33
14664     maize      Tamil Nadu  2015         10000.00
15604     maize      Tamil Nadu  2017          9739.86
8360      maize  Andhra Pradesh  2008          9739.65
8348      maize  Andhra Pradesh  2005          9524.14

In [6]:
def flag_outliers_iqr(df, group_col, value_col, factor=3):
    def bounds(x):
        q1, q3 = x.quantile(0.25), x.quantile(0.75)
        iqr = q3 - q1
        return q1 - factor*iqr, q3 + factor*iqr
    
    outlier_mask = pd.Series(False, index=df.index)
    for crop, group in df.groupby(group_col):
        low, high = bounds(group[value_col])
        mask = (df[group_col] == crop) & ((df[value_col] < low) | (df[value_col] > high))
        outlier_mask |= mask
    return outlier_mask

outliers = flag_outliers_iqr(df1, 'Crop', 'Yield_kg_per_ha')
print("Number of outlier rows:", outliers.sum())
print(df1[outliers][['Crop','State Name','Year','Yield_kg_per_ha']])

Number of outlier rows: 356
         Crop    State Name  Year  Yield_kg_per_ha
134    cotton  Chhattisgarh  2008          1000.00
680    cotton  Chhattisgarh  1974          1000.00
696    cotton  Chhattisgarh  1978          1000.00
709    cotton  Chhattisgarh  1982          1000.00
953    cotton  Chhattisgarh  2008          1000.00
...       ...           ...   ...              ...
48956   maize         Bihar  2015          5582.71
48959   maize         Bihar  2016          8772.46
48962   maize         Bihar  2017          6940.78
49571   maize         Bihar  2012          5727.31
49574   maize         Bihar  2013          5609.44

[356 rows x 4 columns]

In [7]:
realistic_max = {
    'rice': 10000,
    'maize': 15000,
    'chickpea': 3000,
    'cotton': 3000
}

def is_impossible(row):
    return row['Yield_kg_per_ha'] > realistic_max[row['Crop']]

impossible_mask = df1.apply(is_impossible, axis=1)
print("Impossible rows:", impossible_mask.sum())
print(df1[impossible_mask][['Crop','State Name','Year','Yield_kg_per_ha']])

Impossible rows: 13
           Crop  State Name  Year  Yield_kg_per_ha
14581    cotton  Tamil Nadu  1978          4500.00
14585    cotton  Tamil Nadu  1980          5000.00
14587    cotton  Tamil Nadu  1981          5000.00
14589    cotton  Tamil Nadu  1982          4000.00
14591    cotton  Tamil Nadu  1983          4000.00
27807  chickpea   Rajasthan  1968          4833.33
28019  chickpea   Rajasthan  1994          3140.04
30669  chickpea     Haryana  1975          3065.81
31269  chickpea     Haryana  2017          5000.00
31641     maize     Haryana  2016         21428.57
31642  chickpea     Haryana  2016          4000.00
48486  chickpea       Bihar  2007         58363.64
48786  chickpea       Bihar  2007         32000.00

In [8]:
drop_indices = [48486, 48786, 31641]
df1_clean = df1.drop(index=drop_indices).reset_index(drop=True)
print("Original rows:", len(df1))
print("Cleaned rows:", len(df1_clean))

Original rows: 50765
Cleaned rows: 50762

In [9]:
df1_clean.columns = (
    df1_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('%', 'pct')
)
print(df1_clean.columns.tolist())

['dist_code', 'year', 'state_code', 'state_name', 'dist_name', 'crop', 'area_ha', 'yield_kg_per_ha', 'n_req_kg_per_ha', 'p_req_kg_per_ha', 'k_req_kg_per_ha', 'total_n_kg', 'total_p_kg', 'total_k_kg', 'temperature_c', 'humidity_pct', 'ph', 'rainfall_mm', 'wind_speed_m_s', 'solar_radiation_mj_m2_day']

In [10]:
df1_clean.to_csv("../data/processed/dataset1_clean.csv", index=False)
print("Saved dataset1_clean.csv")

Saved dataset1_clean.csv

In [11]:
df3 = pd.read_csv("../data/raw/NPK-based.csv")
print(df3.shape)
df3.info()
print("\nDuplicate rows:", df3.duplicated().sum())
print("\nNull counts:\n", df3.isnull().sum())
print("\nUnique crops:", df3['label'].nunique())
print(sorted(df3['label'].unique()))

(2200, 8)
<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB

Duplicate rows: 0

Null counts:
 N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

Unique crops: 22
['apple', 'banana', 'blackgram', 'chickpea', 'coconut', 'coffee', 'cotton', 'grapes', 'jute', 'kidneybeans', 'lentil', 'maize', 'mango', 'mothbeans', 'mungbean', 'muskmelon', 'orange', 'papaya', 'pigeonpeas', 'pomegranate', 'rice', 'watermelon']

In [12]:
print(df3.describe())

                 N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091    25.616244    71.481779
std      36.917334    32.985883    50.647931     5.063749    22.263812
min       0.000000     5.000000     5.000000     8.825675    14.258040
25%      21.000000    28.000000    20.000000    22.769375    60.261953
50%      37.000000    51.000000    32.000000    25.598693    80.473146
75%      84.250000    68.000000    49.000000    28.561654    89.948771
max     140.000000   145.000000   205.000000    43.675493    99.981876

                ph     rainfall
count  2200.000000  2200.000000
mean      6.469480   103.463655
std       0.773938    54.958389
min       3.504752    20.211267
25%       5.971693    64.551686
50%       6.425045    94.867624
75%       6.923643   124.267508
max       9.935091   298.560117

In [13]:
df3_clean = df3.copy()
df3_clean.columns = df3_clean.columns.str.strip().str.lower()
df3_clean = df3_clean.rename(columns={'label': 'crop'})
print(df3_clean.columns.tolist())

['n', 'p', 'k', 'temperature', 'humidity', 'ph', 'rainfall', 'crop']

In [14]:
df3_clean.to_csv("../data/processed/dataset3_clean.csv", index=False)
print("Saved dataset3_clean.csv")

Saved dataset3_clean.csv

In [1]:
import pandas as pd
import numpy as np

df1 = pd.read_csv("../data/processed/dataset1_clean.csv")
season = pd.read_csv("../data/processed/dataset2_season_lookup.csv")

print(df1.shape)
print(season.shape)
print(df1.columns.tolist())
print(season.columns.tolist())

(50762, 20)
(56811, 5)
['dist_code', 'year', 'state_code', 'state_name', 'dist_name', 'crop', 'area_ha', 'yield_kg_per_ha', 'n_req_kg_per_ha', 'p_req_kg_per_ha', 'k_req_kg_per_ha', 'total_n_kg', 'total_p_kg', 'total_k_kg', 'temperature_c', 'humidity_pct', 'ph', 'rainfall_mm', 'wind_speed_m_s', 'solar_radiation_mj_m2_day']
['state_name', 'district_name', 'year', 'season', 'crop']

In [2]:
df1['state_name_norm'] = df1['state_name'].str.strip().str.lower()
df1['dist_name_norm'] = df1['dist_name'].str.strip().str.lower()
season['state_name_norm'] = season['state_name'].str.strip().str.lower()
season['district_name_norm'] = season['district_name'].str.strip().str.lower()

states_df1 = set(df1['state_name_norm'].unique())
states_season = set(season['state_name_norm'].unique())

print("States in df1 not in season:", states_df1 - states_season)
print("States in season not in df1:", states_season - states_df1)

States in df1 not in season: {'orissa'}
States in season not in df1: {'dadra and nagar haveli', 'manipur', 'chandigarh', 'mizoram', 'sikkim', 'delhi', 'odisha', 'andaman and nicobar islands', 'daman and diu', 'tripura', 'meghalaya', 'jammu and kashmir', 'goa', 'arunachal pradesh', 'nagaland', 'puducherry'}

In [5]:
season['state_name_norm'] = season['state_name_norm'].replace('odisha', 'orissa')

In [6]:
common_states = states_df1 & set(season['state_name_norm'].unique())
print("Common states:", len(common_states))

# check district match rate within common states
df1_common = df1[df1['state_name_norm'].isin(common_states)]
season_common = season[season['state_name_norm'].isin(common_states)]

districts_df1 = set(df1_common['dist_name_norm'].unique())
districts_season = set(season_common['district_name_norm'].unique())

print("Districts in df1:", len(districts_df1))
print("Districts in season:", len(districts_season))
print("Exact matches:", len(districts_df1 & districts_season))
print("\nSample mismatches (in df1 not in season):", list(districts_df1 - districts_season)[:20])

Common states: 20
Districts in df1: 311
Districts in season: 604
Exact matches: 242

Sample mismatches (in df1 not in season): ['singhbhum', 'santhal paragana / dumka', 'roopnagar / ropar', 'palamau', 'shimoge', 'dangs', 'balasore', 'eranakulam', 'rae-bareily', 'mahendragarh / narnaul', 'cooch behar', 'chickmagalur', 'purnea', 'bilashpur', 'swami madhopur', 'champaran', 'pithorgarh', 'panchmahal', 'kanpur', 'garhwal']

In [7]:
season_state_level = (
    season.groupby(['state_name_norm', 'crop', 'year'])['season']
    .agg(lambda x: x.mode()[0])
    .reset_index()
)
print(season_state_level.shape)
print(season_state_level.head())

df1_merged = df1.merge(
    season_state_level,
    on=['state_name_norm', 'crop', 'year'],
    how='left'
)

print(df1_merged.shape)
print("Rows with season matched:", df1_merged['season'].notna().sum())
print("Rows with season missing:", df1_merged['season'].isna().sum())

(2441, 4)
               state_name_norm   crop  year  season
0  andaman and nicobar islands  maize  2007    Rabi
1  andaman and nicobar islands  maize  2008  Summer
2  andaman and nicobar islands  maize  2009  Summer
3  andaman and nicobar islands  maize  2010    Rabi
4  andaman and nicobar islands  maize  2011    Rabi
(50762, 23)
Rows with season matched: 19755
Rows with season missing: 31007

In [8]:
print(season['state_name_norm'].unique())

<StringArray>
['andaman and nicobar islands',              'andhra pradesh',
           'arunachal pradesh',                       'assam',
                       'bihar',                  'chandigarh',
                'chhattisgarh',      'dadra and nagar haveli',
                         'goa',                     'gujarat',
                     'haryana',            'himachal pradesh',
           'jammu and kashmir',                   'jharkhand',
                   'karnataka',                      'kerala',
              'madhya pradesh',                 'maharashtra',
                     'manipur',                   'meghalaya',
                     'mizoram',                    'nagaland',
                      'orissa',                  'puducherry',
                      'punjab',                   'rajasthan',
                      'sikkim',                  'tamil nadu',
                   'telangana',                     'tripura',
               'uttar pradesh',                 'uttarakhand',
                 'west bengal',               'daman and diu',
                       'delhi']
Length: 35, dtype: str

In [11]:
season['state_name_norm'] = season['state_name_norm'].replace('odisha', 'orissa')

In [10]:
df1_keys = set(zip(df1['state_name_norm'], df1['crop'], df1['year']))
season_keys = set(zip(season_state_level['state_name_norm'], season_state_level['crop'], season_state_level['year']))

print("df1 keys:", len(df1_keys))
print("season keys:", len(season_keys))
print("overlap:", len(df1_keys & season_keys))

# check year range overlap specifically
print("\ndf1 year range:", df1['year'].min(), df1['year'].max())
print("season year range:", season['year'].min(), season['year'].max())

df1 keys: 3833
season keys: 2441
overlap: 1461

df1 year range: 1966 2017
season year range: 1997 2020

In [12]:
# Check what seasons actually occur for each of our 4 crops in the season dataset, to get real proportions

print(season.groupby('crop')['season'].value_counts())

crop      season
chickpea  Rabi           9621
          Whole Year      153
          Kharif           94
          Winter           15
cotton    Kharif         5122
          Whole Year      366
          Rabi            360
          Summer           34
          Winter            1
          Autumn            1
maize     Kharif        10228
          Rabi           4129
          Summer         3313
          Autumn         1430
          Whole Year      228
          Winter           97
rice      Kharif         9885
          Summer         3914
          Winter         3298
          Autumn         3079
          Rabi           1316
          Whole Year      127
Name: count, dtype: int64

In [13]:
default_season = {
    'chickpea': 'Rabi',
    'cotton': 'Kharif',
    'maize': 'Kharif',
    'rice': 'Kharif'
}

df1['season'] = df1['crop'].map(default_season)
print(df1[['crop','season']].drop_duplicates())
print(df1['season'].value_counts())

         crop  season
0        rice  Kharif
1       maize  Kharif
2    chickpea    Rabi
111    cotton  Kharif
season
Kharif    36917
Rabi      13845
Name: count, dtype: int64

In [14]:
default_season = {
    'chickpea': 'Rabi',
    'cotton': 'Kharif',
    'maize': 'Kharif',
    'rice': 'Kharif'
}

df1['season'] = df1['crop'].map(default_season)
print(df1[['crop','season']].drop_duplicates())
print(df1['season'].value_counts())

         crop  season
0        rice  Kharif
1       maize  Kharif
2    chickpea    Rabi
111    cotton  Kharif
season
Kharif    36917
Rabi      13845
Name: count, dtype: int64

In [15]:
# drop helper columns we no longer need
df1_final = df1.drop(columns=['state_name_norm', 'dist_name_norm'], errors='ignore')
df1_final.to_csv("../data/processed/dataset1_with_season.csv", index=False)
print(df1_final.shape)
print(df1_final.columns.tolist())
print("Saved dataset1_with_season.csv")

(50762, 21)
['dist_code', 'year', 'state_code', 'state_name', 'dist_name', 'crop', 'area_ha', 'yield_kg_per_ha', 'n_req_kg_per_ha', 'p_req_kg_per_ha', 'k_req_kg_per_ha', 'total_n_kg', 'total_p_kg', 'total_k_kg', 'temperature_c', 'humidity_pct', 'ph', 'rainfall_mm', 'wind_speed_m_s', 'solar_radiation_mj_m2_day', 'season']
Saved dataset1_with_season.csv

In [16]:
print(df1[df1['state_name'].isin(['Telangana', 'Andhra Pradesh'])].groupby(['state_name','year']).size().unstack(fill_value=0))

year            1966  1967  1968  1969  1970  1971  1972  1973  1974  1975  \
state_name
Andhra Pradesh    37    36    34    34    36    37    34    37    37    37
Telangana         31    33    30    34    34    33    32    33    36    32

year            ...  2008  2009  2010  2011  2012  2013  2014  2015  2016  \
state_name      ...
Andhra Pradesh  ...    43    43    42    42    43    43    44    43    42
Telangana       ...    36    36    36    36    36    36    36    35    36

year            2017
state_name
Andhra Pradesh    43
Telangana         36

[2 rows x 52 columns]

In [17]:
ap_districts = set(df1[df1['state_name']=='Andhra Pradesh']['dist_name'].unique())
tg_districts = set(df1[df1['state_name']=='Telangana']['dist_name'].unique())
print("Shared district names between AP and Telangana:", ap_districts & tg_districts)
print("AP district count:", len(ap_districts))
print("Telangana district count:", len(tg_districts))

Shared district names between AP and Telangana: set()
AP district count: 11
Telangana district count: 9

In [1]:
import pandas as pd
import numpy as np

df1 = pd.read_csv("../data/processed/dataset1_with_season.csv")
print(df1.shape)
df1.head()

(50762, 21)

,dist_code,year,state_code,state_name,dist_name,crop,area_ha,yield_kg_per_ha,n_req_kg_per_ha,p_req_kg_per_ha,...,total_n_kg,total_p_kg,total_k_kg,temperature_c,humidity_pct,ph,rainfall_mm,wind_speed_m_s,solar_radiation_mj_m2_day,season
0,1,1966,14,Chhattisgarh,Durg,rice,548000.0,337.59,8.43975,4.05108,...,4624983.00,2219991.84,4069985.04,25,80,6.5,1200,2.0,18,Kharif
1,1,1966,14,Chhattisgarh,Durg,maize,3000.0,666.67,18.00009,8.00004,...,54000.27,24000.12,34000.17,22,70,6.0,800,2.5,20,Kharif
2,1,1966,14,Chhattisgarh,Durg,chickpea,54000.0,500.00,9.00000,5.00000,...,486000.00,270000.00,486000.00,20,60,6.5,600,1.5,16,Rabi
3,1,1967,14,Chhattisgarh,Durg,rice,547000.0,747.71,18.69275,8.97252,...,10224934.25,4907968.44,8997942.14,25,80,6.5,1200,2.0,18,Kharif
4,1,1967,14,Chhattisgarh,Durg,maize,3000.0,1000.00,27.00000,12.00000,...,81000.00,36000.00,51000.00,22,70,6.0,800,2.5,20,Kharif

In [2]:
print(df1.groupby('crop')[['n_req_kg_per_ha','p_req_kg_per_ha','k_req_kg_per_ha']].nunique())

          n_req_kg_per_ha  p_req_kg_per_ha  k_req_kg_per_ha
crop
chickpea             8491             8491             8491
cotton               4932             4932             4932
maize                9170             9170             9170
rice                12905            12905            12905

In [3]:
sample = df1[df1['crop']=='rice'][['dist_name','year','n_req_kg_per_ha','p_req_kg_per_ha','k_req_kg_per_ha']].sort_values(['dist_name','year'])
print(sample.head(20))

         dist_name  year  n_req_kg_per_ha  p_req_kg_per_ha  k_req_kg_per_ha
46130  24 Parganas  1966         26.02475         12.49188         22.90178
46133  24 Parganas  1967         27.55900         13.22832         24.25192
46136  24 Parganas  1968         28.56475         13.71108         25.13698
46139  24 Parganas  1969         26.53950         12.73896         23.35476
46142  24 Parganas  1970         20.41975          9.80148         17.96938
46145  24 Parganas  1971         23.06100         11.06928         20.29368
46148  24 Parganas  1972         25.21200         12.10176         22.18656
46151  24 Parganas  1973         28.36025         13.61292         24.95702
46153  24 Parganas  1974         29.60900         14.21232         26.05592
46156  24 Parganas  1975         30.26875         14.52900         26.63650
46159  24 Parganas  1976         26.28575         12.61716         23.13146
46162  24 Parganas  1977         34.17675         16.40484         30.07554
46164  24 Parganas  1978         27.64350         13.26888         24.32628
46166  24 Parganas  1979         27.85325         13.36956         24.51086
46169  24 Parganas  1980         36.19950         17.37576         31.85556
46172  24 Parganas  1981         26.39325         12.66876         23.22606
46175  24 Parganas  1982         24.00025         11.52012         21.12022
46178  24 Parganas  1983         36.10150         17.32872         31.76932
46181  24 Parganas  1984         40.48400         19.43232         35.62592
46183  24 Parganas  1985         34.48275         16.55172         30.34482

In [4]:
print(df1[['n_req_kg_per_ha','p_req_kg_per_ha','k_req_kg_per_ha','area_ha','yield_kg_per_ha']].corr())

                 n_req_kg_per_ha  p_req_kg_per_ha  k_req_kg_per_ha   area_ha  \
n_req_kg_per_ha         1.000000         0.997116         0.966151  0.153463
p_req_kg_per_ha         0.997116         1.000000         0.980276  0.167888
k_req_kg_per_ha         0.966151         0.980276         1.000000  0.232897
area_ha                 0.153463         0.167888         0.232897  1.000000
yield_kg_per_ha         0.991957         0.998035         0.979446  0.159212

                 yield_kg_per_ha
n_req_kg_per_ha         0.991957
p_req_kg_per_ha         0.998035
k_req_kg_per_ha         0.979446
area_ha                 0.159212
yield_kg_per_ha         1.000000

In [5]:
feature_cols = ['state_name', 'crop', 'season', 'area_ha', 'temperature_c', 
                 'humidity_pct', 'ph', 'rainfall_mm', 'wind_speed_m_s', 
                 'solar_radiation_mj_m2_day']
target_col = 'yield_kg_per_ha'

df_model = df1[feature_cols + [target_col]].copy()
print(df_model.shape)
print(df_model.head())
print(df_model.isnull().sum())

(50762, 11)
     state_name      crop  season   area_ha  temperature_c  humidity_pct   ph  \
0  Chhattisgarh      rice  Kharif  548000.0             25            80  6.5
1  Chhattisgarh     maize  Kharif    3000.0             22            70  6.0
2  Chhattisgarh  chickpea    Rabi   54000.0             20            60  6.5
3  Chhattisgarh      rice  Kharif  547000.0             25            80  6.5
4  Chhattisgarh     maize  Kharif    3000.0             22            70  6.0

   rainfall_mm  wind_speed_m_s  solar_radiation_mj_m2_day  yield_kg_per_ha
0         1200             2.0                         18           337.59
1          800             2.5                         20           666.67
2          600             1.5                         16           500.00
3         1200             2.0                         18           747.71
4          800             2.5                         20          1000.00
state_name                   0
crop                         0
season                       0
area_ha                      0
temperature_c                0
humidity_pct                 0
ph                           0
rainfall_mm                  0
wind_speed_m_s               0
solar_radiation_mj_m2_day    0
yield_kg_per_ha              0
dtype: int64

In [6]:
for col in ['temperature_c','humidity_pct','ph','rainfall_mm','wind_speed_m_s','solar_radiation_mj_m2_day']:
    print(col, ":", sorted(df_model[col].unique()))

temperature_c : [np.int64(20), np.int64(22), np.int64(25), np.int64(28)]
humidity_pct : [np.int64(60), np.int64(65), np.int64(70), np.int64(80)]
ph : [np.float64(6.0), np.float64(6.5)]
rainfall_mm : [np.int64(600), np.int64(700), np.int64(800), np.int64(1200)]
wind_speed_m_s : [np.float64(1.5), np.float64(2.0), np.float64(2.5), np.float64(3.0)]
solar_radiation_mj_m2_day : [np.int64(16), np.int64(18), np.int64(20), np.int64(22)]

In [7]:
print(df_model.groupby('crop')[['temperature_c','humidity_pct','ph','rainfall_mm','wind_speed_m_s','solar_radiation_mj_m2_day']].nunique())

          temperature_c  humidity_pct  ph  rainfall_mm  wind_speed_m_s  \
crop
chickpea              1             1   1            1               1
cotton                1             1   1            1               1
maize                 1             1   1            1               1
rice                  1             1   1            1               1

          solar_radiation_mj_m2_day
crop
chickpea                          1
cotton                            1
maize                             1
rice                              1

In [8]:
print("Total rows:", len(df1))
print("Rows from 1981 onward:", (df1['year'] >= 1981).sum())
print("Rows before 1981:", (df1['year'] < 1981).sum())

Total rows: 50762
Rows from 1981 onward: 36253
Rows before 1981: 14509

In [9]:
df1_recent = df1[df1['year'] >= 1981].copy()
df1_recent.to_csv("../data/processed/dataset1_1981_onward.csv", index=False)
print(df1_recent.shape)

(36253, 21)

In [10]:
districts = df1_recent[['state_name','dist_name']].drop_duplicates().reset_index(drop=True)
print(districts.shape)
districts.head()

(311, 2)

     state_name dist_name
0  Chhattisgarh      Durg
1  Chhattisgarh    Bastar
2  Chhattisgarh    Raipur
3  Chhattisgarh  Bilaspur
4  Chhattisgarh   Raigarh

In [11]:
import requests
import time

def geocode_district(district, state, country="India"):
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": f"{district}, {state}, {country}",
        "format": "json",
        "limit": 1
    }
    headers = {"User-Agent": "AgriVisionAI/1.0"}
    try:
        resp = requests.get(url, params=params, headers=headers, timeout=10)
        data = resp.json()
        if data:
            return float(data[0]['lat']), float(data[0]['lon'])
    except Exception as e:
        print(f"Error for {district}, {state}: {e}")
    return None, None

# test on first 5 before running all 311
for i in range(5):
    d, s = districts.loc[i, 'dist_name'], districts.loc[i, 'state_name']
    lat, lon = geocode_district(d, s)
    print(d, s, "->", lat, lon)
    time.sleep(1)  # Nominatim requires max 1 request/sec

Durg Chhattisgarh -> 21.1982964 81.4007922
Bastar Chhattisgarh -> 19.1191283 81.8291865
Raipur Chhattisgarh -> 21.2380912 81.6336993
Bilaspur Chhattisgarh -> 22.1638486 82.1365923
Raigarh Chhattisgarh -> 22.2361795 83.3529534

In [12]:
lats, lons = [], []
failed = []

for i, row in districts.iterrows():
    d, s = row['dist_name'], row['state_name']
    lat, lon = geocode_district(d, s)
    lats.append(lat)
    lons.append(lon)
    if lat is None:
        failed.append((d, s))
    if i % 20 == 0:
        print(f"Progress: {i}/{len(districts)}")
    time.sleep(1)

districts['latitude'] = lats
districts['longitude'] = lons

print("Total failed:", len(failed))
print(failed)

Progress: 0/311
Progress: 20/311
Progress: 40/311
Progress: 60/311
Progress: 80/311
Progress: 100/311
Progress: 120/311
Progress: 140/311
Progress: 160/311
Progress: 180/311
Progress: 200/311
Progress: 220/311
Progress: 240/311
Progress: 260/311
Progress: 280/311
Progress: 300/311
Total failed: 22
[('Khandwa / East Nimar', 'Madhya Pradesh'), ('Shimoge', 'Karnataka'), ('Chickmagalur', 'Karnataka'), ('Chengalpattu MGR / Kanchipuram', 'Tamil Nadu'), ('North Arcot / Vellore', 'Tamil Nadu'), ('Ramananthapuram', 'Tamil Nadu'), ('Amarawati', 'Maharashtra'), ('Yeotmal', 'Maharashtra'), ('Swami Madhopur', 'Rajasthan'), ('Buland Shahar', 'Uttar Pradesh'), ('Mirzpur', 'Uttar Pradesh'), ('Rae-Bareily', 'Uttar Pradesh'), ('Almorah', 'Uttarakhand'), ('Pithorgarh', 'Uttarakhand'), ('Uttar Kashi', 'Uttarakhand'), ('North Cachar Hil / Dima hasao', 'Assam'), ('Bilashpur', 'Himachal Pradesh'), ('Lahul & Spiti', 'Himachal Pradesh'), ('Mayurbhanja', 'Orissa'), ('Mungair', 'Bihar'), ('Santhal Paragana / Dumka', 'Jharkhand'), ('Shahabad (now part of Bhojpur district)', 'Bihar')]

In [13]:
manual_fixes = {
    'Khandwa / East Nimar': 'Khandwa',
    'Shimoge': 'Shimoga',
    'Chickmagalur': 'Chikmagalur',
    'Chengalpattu MGR / Kanchipuram': 'Kanchipuram',
    'North Arcot / Vellore': 'Vellore',
    'Ramananthapuram': 'Ramanathapuram',
    'Amarawati': 'Amravati',
    'Yeotmal': 'Yavatmal',
    'Swami Madhopur': 'Sawai Madhopur',
    'Buland Shahar': 'Bulandshahr',
    'Mirzpur': 'Mirzapur',
    'Rae-Bareily': 'Raebareli',
    'Almorah': 'Almora',
    'Pithorgarh': 'Pithoragarh',
    'Uttar Kashi': 'Uttarkashi',
    'North Cachar Hil / Dima hasao': 'Dima Hasao',
    'Bilashpur': 'Bilaspur',
    'Lahul & Spiti': 'Lahaul and Spiti',
    'Mayurbhanja': 'Mayurbhanj',
    'Mungair': 'Munger',
    'Santhal Paragana / Dumka': 'Dumka',
    'Shahabad (now part of Bhojpur district)': 'Bhojpur'
}

for orig_name, fixed_name in manual_fixes.items():
    state = districts.loc[districts['dist_name']==orig_name, 'state_name'].values[0]
    lat, lon = geocode_district(fixed_name, state)
    districts.loc[districts['dist_name']==orig_name, 'latitude'] = lat
    districts.loc[districts['dist_name']==orig_name, 'longitude'] = lon
    print(orig_name, "->", fixed_name, ":", lat, lon)
    time.sleep(1)

print("\nRemaining nulls:", districts['latitude'].isnull().sum())

Khandwa / East Nimar -> Khandwa : 21.9769779 76.5675344
Shimoge -> Shimoga : 14.0556503 75.2380553
Chickmagalur -> Chikmagalur : 13.318014 75.7738743
Chengalpattu MGR / Kanchipuram -> Kanchipuram : 12.9647163 79.9839686
North Arcot / Vellore -> Vellore : 12.9021849 79.061104
Ramananthapuram -> Ramanathapuram : 9.5205576 78.5184635
Amarawati -> Amravati : 21.1545412 77.6442962
Yeotmal -> Yavatmal : 20.0638677 78.3565663
Swami Madhopur -> Sawai Madhopur : 26.2290186 76.3043561
Buland Shahar -> Bulandshahr : 28.3874073 77.9743805
Mirzpur -> Mirzapur : 24.9316896 82.6280163
Rae-Bareily -> Raebareli : 26.2086769 81.2186298
Almorah -> Almora : 29.702651 79.4326318
Pithorgarh -> Pithoragarh : 29.585871 80.215167
Uttar Kashi -> Uttarkashi : 30.9635733 78.6362521
North Cachar Hil / Dima hasao -> Dima Hasao : 25.4003625 93.0752292
Bilashpur -> Bilaspur : 31.3380959 76.7611631
Lahul & Spiti -> Lahaul and Spiti : 32.5015861 77.5789891
Mayurbhanja -> Mayurbhanj : 21.9156338 86.3961824
Mungair -> Munger : 25.2202864 86.5161484
Santhal Paragana / Dumka -> Dumka : 24.2677937 87.2485495
Shahabad (now part of Bhojpur district) -> Bhojpur : 25.4501182 84.5635193

Remaining nulls: 0

In [14]:
districts.to_csv("../data/processed/district_coordinates.csv", index=False)
print("Saved district_coordinates.csv")
print(districts.shape)

Saved district_coordinates.csv
(311, 4)

In [15]:
import requests

def get_nasa_power_annual(lat, lon, start_year=1981, end_year=2017):
    url = "https://power.larc.nasa.gov/api/temporal/monthly/point"
    params = {
        "parameters": "T2M,RH2M,PRECTOTCORR,WS2M,ALLSKY_SFC_SW_DWN",
        "community": "AG",
        "longitude": lon,
        "latitude": lat,
        "start": start_year,
        "end": end_year,
        "format": "JSON"
    }
    resp = requests.get(url, params=params, timeout=30)
    return resp.json()

# test on Durg, Chhattisgarh
test_data = get_nasa_power_annual(21.1982964, 81.4007922)
print(test_data.keys())

dict_keys(['type', 'geometry', 'properties', 'header', 'messages', 'parameters', 'times'])

In [16]:
print(test_data['properties'].keys())

dict_keys(['parameter'])

In [17]:
params_data = test_data['properties']['parameter']
print(params_data.keys())

# look at one parameter's structure
print(list(params_data['T2M'].items())[:15])

dict_keys(['ALLSKY_SFC_SW_DWN', 'PRECTOTCORR', 'RH2M', 'T2M', 'WS2M'])
[('198101', 17.55), ('198102', 22.43), ('198103', 26.37), ('198104', 32.72), ('198105', 33.69), ('198106', 31.97), ('198107', 26.43), ('198108', 25.92), ('198109', 25.78), ('198110', 23.71), ('198111', 19.69), ('198112', 17.57), ('198113', 25.32), ('198201', 20.69), ('198202', 21.41)]

In [18]:
def extract_annual_values(param_dict, start_year=1981, end_year=2017):
    annual = {}
    for year in range(start_year, end_year + 1):
        key = f"{year}13"  # the 13th "month" = annual average
        if key in param_dict:
            annual[year] = param_dict[key]
    return annual

t2m_annual = extract_annual_values(params_data['T2M'])
print(list(t2m_annual.items())[:5])
print("Total years captured:", len(t2m_annual))

[(1981, 25.32), (1982, 25.72), (1983, 26.1), (1984, 26.04), (1985, 26.42)]
Total years captured: 37

In [20]:
def get_district_weather(lat, lon, start_year=1981, end_year=2017):
    url = "https://power.larc.nasa.gov/api/temporal/monthly/point"
    params = {
        "parameters": "T2M,RH2M,PRECTOTCORR,WS2M,ALLSKY_SFC_SW_DWN",
        "community": "AG",
        "longitude": lon,
        "latitude": lat,
        "start": start_year,
        "end": end_year,
        "format": "JSON"
    }
    try:
        resp = requests.get(url, params=params, timeout=30)
        data = resp.json()
        param_data = data['properties']['parameter']
        
        rows = []
        for year in range(start_year, end_year + 1):
            key = f"{year}13"
            row = {
                'year': year,
                'temperature_c': param_data['T2M'].get(key),
                'humidity_pct': param_data['RH2M'].get(key),
                'rainfall_mm': param_data['PRECTOTCORR'].get(key),
                'wind_speed_m_s': param_data['WS2M'].get(key),
                'solar_radiation_mj_m2_day': param_data['ALLSKY_SFC_SW_DWN'].get(key)
            }
            rows.append(row)
        return rows
    except Exception as e:
        print(f"Error: {e}")
        return None

In [21]:
test_result = get_district_weather(21.1982964, 81.4007922)
print(len(test_result))
print(test_result[:3])

37
[{'year': 1981, 'temperature_c': 25.32, 'humidity_pct': 62.78, 'rainfall_mm': 4.48, 'wind_speed_m_s': 2.1, 'solar_radiation_mj_m2_day': -999.0}, {'year': 1982, 'temperature_c': 25.72, 'humidity_pct': 65.83, 'rainfall_mm': 4.57, 'wind_speed_m_s': 2.04, 'solar_radiation_mj_m2_day': -999.0}, {'year': 1983, 'temperature_c': 26.1, 'humidity_pct': 56.03, 'rainfall_mm': 2.85, 'wind_speed_m_s': 2.17, 'solar_radiation_mj_m2_day': -999.0}]

In [22]:
# Check solar radiation availability by year
solar_test = get_district_weather(21.1982964, 81.4007922, start_year=1981, end_year=1990)
for row in solar_test:
    print(row['year'], row['solar_radiation_mj_m2_day'])

1981 -999.0
1982 -999.0
1983 -999.0
1984 19.5
1985 19.94
1986 20.07
1987 19.13
1988 19.17
1989 19.77
1990 18.83

In [23]:
print("Daily rate:", solar_test[5]['rainfall_mm'], "-> Annual estimate:", solar_test[5]['rainfall_mm'] * 365)

Daily rate: 3.94 -> Annual estimate: 1438.1

In [24]:
print("Rows 1984 onward:", (df1_recent['year'] >= 1984).sum())
print("Rows 1981-1983:", ((df1_recent['year'] >= 1981) & (df1_recent['year'] < 1984)).sum())

Rows 1984 onward: 33268
Rows 1981-1983: 2985

In [26]:
def get_district_weather(lat, lon, start_year=1984, end_year=2017):
    url = "https://power.larc.nasa.gov/api/temporal/monthly/point"
    params = {
        "parameters": "T2M,RH2M,PRECTOTCORR,WS2M,ALLSKY_SFC_SW_DWN",
        "community": "AG",
        "longitude": lon,
        "latitude": lat,
        "start": start_year,
        "end": end_year,
        "format": "JSON"
    }
    try:
        resp = requests.get(url, params=params, timeout=30)
        data = resp.json()
        param_data = data['properties']['parameter']
        
        rows = []
        for year in range(start_year, end_year + 1):
            key = f"{year}13"
            row = {
                'year': year,
                'temperature_c': param_data['T2M'].get(key),
                'humidity_pct': param_data['RH2M'].get(key),
                'rainfall_mm': param_data['PRECTOTCORR'].get(key, 0) * 365,  # convert daily rate to annual total
                'wind_speed_m_s': param_data['WS2M'].get(key),
                'solar_radiation_mj_m2_day': param_data['ALLSKY_SFC_SW_DWN'].get(key)
            }
            rows.append(row)
        return rows
    except Exception as e:
        print(f"Error: {e}")
        return None

In [27]:
all_weather = []
failed_districts = []

for i, row in districts.iterrows():
    lat, lon = row['latitude'], row['longitude']
    weather_rows = get_district_weather(lat, lon)
    if weather_rows is None:
        failed_districts.append((row['dist_name'], row['state_name']))
        continue
    for w in weather_rows:
        w['dist_name'] = row['dist_name']
        w['state_name'] = row['state_name']
        all_weather.append(w)
    if i % 20 == 0:
        print(f"Progress: {i}/{len(districts)}")
    time.sleep(1)

weather_df = pd.DataFrame(all_weather)
print(weather_df.shape)
print("Failed districts:", len(failed_districts), failed_districts)
weather_df.head()

Progress: 0/311
Progress: 20/311
Progress: 40/311
Progress: 60/311
Progress: 80/311
Progress: 100/311
Progress: 120/311
Progress: 140/311
Progress: 160/311
Progress: 180/311
Progress: 200/311
Progress: 220/311
Progress: 240/311
Progress: 260/311
Progress: 280/311
Progress: 300/311
(10574, 8)
Failed districts: 0 []

,year,temperature_c,humidity_pct,rainfall_mm,wind_speed_m_s,solar_radiation_mj_m2_day,dist_name,state_name
0,1984,26.04,57.02,1146.10,2.14,19.50,Durg,Chhattisgarh
1,1985,26.42,56.26,1193.55,2.12,19.94,Durg,Chhattisgarh
2,1986,25.99,61.27,1438.10,2.11,20.07,Durg,Chhattisgarh
3,1987,26.39,56.31,916.15,2.20,19.13,Durg,Chhattisgarh
4,1988,27.32,50.41,682.55,2.09,19.17,Durg,Chhattisgarh

In [28]:
weather_df.to_csv("../data/processed/real_weather_by_district_year.csv", index=False)
print("Saved real_weather_by_district_year.csv")

Saved real_weather_by_district_year.csv

In [29]:
df1_1984on = df1_recent[df1_recent['year'] >= 1984].copy()

# drop old fake weather columns
old_weather_cols = ['temperature_c','humidity_pct','ph','rainfall_mm','wind_speed_m_s','solar_radiation_mj_m2_day']
df1_no_weather = df1_1984on.drop(columns=old_weather_cols)

# merge real weather on dist_name + state_name + year
df1_real_weather = df1_no_weather.merge(
    weather_df,
    on=['dist_name','state_name','year'],
    how='left'
)

print(df1_real_weather.shape)
print("Rows with matched weather:", df1_real_weather['temperature_c'].notna().sum())
print("Rows missing weather:", df1_real_weather['temperature_c'].isna().sum())

(33268, 20)
Rows with matched weather: 33268
Rows missing weather: 0

In [1]:
import pandas as pd
import numpy as np
import requests
import time

districts = pd.read_csv("../data/processed/district_coordinates.csv")
df1 = pd.read_csv("../data/processed/dataset1_real_weather_final.csv")
print(districts.shape)
print(df1.shape)

(311, 4)
(33268, 20)

In [2]:
def get_soilgrids_ph(lat, lon):
    url = "https://rest.isric.org/soilgrids/v2.0/properties/query"
    params = {
        "lon": lon,
        "lat": lat,
        "property": "phh2o",
        "depth": "0-5cm",
        "value": "mean"
    }
    try:
        resp = requests.get(url, params=params, timeout=30)
        data = resp.json()
        return data
    except Exception as e:
        print(f"Error: {e}")
        return None

# test on Durg, Chhattisgarh
test_soil = get_soilgrids_ph(21.1982964, 81.4007922)
print(test_soil)

{'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [81.4007922, 21.1982964]}, 'properties': {'layers': [{'name': 'phh2o', 'unit_measure': {'d_factor': 10, 'mapped_units': 'pH*10', 'target_units': '-', 'uncertainty_unit': ''}, 'depths': [{'range': {'top_depth': 0, 'bottom_depth': 5, 'unit_depth': 'cm'}, 'label': '0-5cm', 'values': {'mean': None}}]}]}, 'query_time_s': 0.24832439422607422}

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, f1_score, classification_report, mean_squared_error, r2_score

df_a = pd.read_csv("../data/processed/dataset3_clean.csv")
df_b = pd.read_csv("../data/processed/model_b_training_data.csv")

print(df_a.shape, df_b.shape)

(2200, 8) (33268, 10)

In [5]:
X_a = df_a.drop(columns=['crop'])
y_a = df_a['crop']

X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(
    X_a, y_a, test_size=0.2, random_state=42, stratify=y_a
)

rf_a = RandomForestClassifier(n_estimators=200, random_state=42)
rf_a.fit(X_train_a, y_train_a)

y_pred_a = rf_a.predict(X_test_a)
print("Accuracy:", accuracy_score(y_test_a, y_pred_a))
print("F1 (macro):", f1_score(y_test_a, y_pred_a, average='macro'))
print(classification_report(y_test_a, y_pred_a))

Accuracy: 0.9954545454545455
F1 (macro): 0.9954517027687758
              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        20
      banana       1.00      1.00      1.00        20
   blackgram       1.00      0.95      0.97        20
    chickpea       1.00      1.00      1.00        20
     coconut       1.00      1.00      1.00        20
      coffee       1.00      1.00      1.00        20
      cotton       1.00      1.00      1.00        20
      grapes       1.00      1.00      1.00        20
        jute       0.95      1.00      0.98        20
 kidneybeans       1.00      1.00      1.00        20
      lentil       1.00      1.00      1.00        20
       maize       0.95      1.00      0.98        20
       mango       1.00      1.00      1.00        20
   mothbeans       1.00      1.00      1.00        20
    mungbean       1.00      1.00      1.00        20
   muskmelon       1.00      1.00      1.00        20
      orange       1.00      1.00      1.00        20
      papaya       1.00      1.00      1.00        20
  pigeonpeas       1.00      1.00      1.00        20
 pomegranate       1.00      1.00      1.00        20
        rice       1.00      0.95      0.97        20
  watermelon       1.00      1.00      1.00        20

    accuracy                           1.00       440
   macro avg       1.00      1.00      1.00       440
weighted avg       1.00      1.00      1.00       440

In [6]:
df_b_encoded = pd.get_dummies(df_b, columns=['state_name', 'crop', 'season'], drop_first=True)
print(df_b_encoded.shape)

X_b = df_b_encoded.drop(columns=['yield_kg_per_ha'])
y_b = df_b_encoded['yield_kg_per_ha']

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X_b, y_b, test_size=0.2, random_state=42
)

rf_b = RandomForestRegressor(n_estimators=200, random_state=42)
rf_b.fit(X_train_b, y_train_b)

y_pred_b = rf_b.predict(X_test_b)
rmse = np.sqrt(mean_squared_error(y_test_b, y_pred_b))
r2 = r2_score(y_test_b, y_pred_b)
print("RMSE:", rmse)
print("R²:", r2)

(33268, 30)
RMSE: 508.2398720889303
R²: 0.7744743972312382

In [7]:
X_b = df_b_encoded.drop(columns=['yield_kg_per_ha'])
y_b = df_b_encoded['yield_kg_per_ha']

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X_b, y_b, test_size=0.2, random_state=42
)

rf_b = RandomForestRegressor(n_estimators=200, random_state=42)
rf_b.fit(X_train_b, y_train_b)

y_pred_b = rf_b.predict(X_test_b)
rmse = np.sqrt(mean_squared_error(y_test_b, y_pred_b))
r2 = r2_score(y_test_b, y_pred_b)
print("RMSE:", rmse)
print("R²:", r2)

RMSE: 508.2398720889303
R²: 0.7744743972312382

In [8]:
print("Mean yield:", y_b.mean())
print("RMSE as % of mean:", (rmse / y_b.mean()) * 100)

Mean yield: 1327.4949936876278
RMSE as % of mean: 38.28563380695687

In [9]:
importances = pd.Series(rf_b.feature_importances_, index=X_b.columns).sort_values(ascending=False)
print(importances.head(15))

season_Rabi                  0.180419
crop_cotton                  0.175085
humidity_pct                 0.107077
area_ha                      0.105989
temperature_c                0.084497
solar_radiation_mj_m2_day    0.068150
wind_speed_m_s               0.058717
state_name_Punjab            0.044510
rainfall_mm                  0.038736
state_name_Orissa            0.018077
state_name_Assam             0.017922
crop_rice                    0.015991
crop_maize                   0.015800
state_name_Karnataka         0.012760
state_name_Telangana         0.012424
dtype: float64

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report

df_a = pd.read_csv("../data/processed/dataset3_clean.csv")
print(df_a.shape)
df_a.head()

(2200, 8)

    n   p   k  temperature   humidity        ph    rainfall  crop
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [2]:
X_a = df_a.drop(columns=['crop'])
y_a = df_a['crop']

le = LabelEncoder()
y_a_encoded = le.fit_transform(y_a)
print("Classes:", le.classes_)
print("Number of classes:", len(le.classes_))

X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(
    X_a, y_a_encoded, test_size=0.2, random_state=42, stratify=y_a_encoded
)

scaler_a = StandardScaler()
X_train_a_scaled = scaler_a.fit_transform(X_train_a)
X_test_a_scaled = scaler_a.transform(X_test_a)

print(X_train_a_scaled.shape, X_test_a_scaled.shape)

Classes: ['apple' 'banana' 'blackgram' 'chickpea' 'coconut' 'coffee' 'cotton'
 'grapes' 'jute' 'kidneybeans' 'lentil' 'maize' 'mango' 'mothbeans'
 'mungbean' 'muskmelon' 'orange' 'papaya' 'pigeonpeas' 'pomegranate'
 'rice' 'watermelon']
Number of classes: 22
(1760, 7) (440, 7)

In [3]:
model_a = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train_a_scaled.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(22, activation='softmax')
])

model_a.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_a.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 22)                  │             726 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,318 (12.96 KB)

 Trainable params: 3,318 (12.96 KB)

 Non-trainable params: 0 (0.00 B)

In [4]:
history_a = model_a.fit(
    X_train_a_scaled, y_train_a,
    validation_split=0.15,
    epochs=100,
    batch_size=16,
    verbose=1,
    callbacks=[tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)]
)

Epoch 1/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1544 - loss: 2.9079 - val_accuracy: 0.3636 - val_loss: 2.5451
Epoch 2/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4164 - loss: 2.1348 - val_accuracy: 0.6780 - val_loss: 1.5730
Epoch 3/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5882 - loss: 1.4209 - val_accuracy: 0.8068 - val_loss: 0.9441
Epoch 4/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6644 - loss: 1.0417 - val_accuracy: 0.8788 - val_loss: 0.6585
Epoch 5/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7233 - loss: 0.8478 - val_accuracy: 0.8864 - val_loss: 0.5012
Epoch 6/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7513 - loss: 0.7225 - val_accuracy: 0.9356 - val_loss: 0.3986
Epoch 7/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7714 - loss: 0.6380 - val_accuracy: 0.9242 - val_loss: 0.3453
Epoch 8/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5528 - val_accuracy: 0.9205 - val_loss: 0.2994
Epoch 9/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8195 - loss: 0.5140 - val_accuracy: 0.9280 - val_loss: 0.2674
Epoch 10/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8396 - loss: 0.4580 - val_accuracy: 0.9318 - val_loss: 0.2428
Epoch 11/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8382 - loss: 0.4512 - val_accuracy: 0.9470 - val_loss: 0.2259
Epoch 12/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8416 - loss: 0.4364 - val_accuracy: 0.9356 - val_loss: 0.2143
Epoch 13/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8483 - loss: 0.3948 - val_accuracy: 0.9545 - val_loss: 0.1810
Epoch 14/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8630 - loss: 0.3834 - val_accuracy: 0.9508 - val_loss: 0.1734
Epoch 15/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8770 - loss: 0.3513 - val_accuracy: 0.9659 - val_loss: 0.1638
Epoch 16/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8783 - loss: 0.3288 - val_accuracy: 0.9621 - val_loss: 0.1524
Epoch 17/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8757 - loss: 0.3385 - val_accuracy: 0.9659 - val_loss: 0.1403
Epoch 18/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8870 - loss: 0.3170 - val_accuracy: 0.9583 - val_loss: 0.1451
Epoch 19/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8897 - loss: 0.3024 - val_accuracy: 0.9621 - val_loss: 0.1302
Epoch 20/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8957 - loss: 0.2855 - val_accuracy: 0.9621 - val_loss: 0.1241
Epoch 21/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9051 - loss: 0.2616 - val_accuracy: 0.9621 - val_loss: 0.1201
Epoch 22/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8971 - loss: 0.2730 - val_accuracy: 0.9583 - val_loss: 0.1188
Epoch 23/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9057 - loss: 0.2539 - val_accuracy: 0.9545 - val_loss: 0.1242
Epoch 24/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9124 - loss: 0.2430 - val_accuracy: 0.9659 - val_loss: 0.1105
Epoch 25/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9178 - loss: 0.2335 - val_accuracy: 0.9583 - val_loss: 0.1081
Epoch 26/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9011 - loss: 0.2452 - val_accuracy: 0.9659 - val_loss: 0.0952
Epoch 27/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9318 - loss: 0.2116 - val_accuracy: 0.9735 - val_loss: 0.0893
Epoch 28/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9245 - loss: 0.2090 - val_accuracy: 0.9659 - val_loss: 0.0921
Epoch 29/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9205 - loss: 0.2241 - val_accuracy: 0.9659 - val_loss: 0.0914
Epoch 30/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9198 - loss: 0.2103 - val_accuracy: 0.9735 - val_loss: 0.0928
Epoch 31/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9231 - loss: 0.2167 - val_accuracy: 0.9735 - val_loss: 0.0916
Epoch 32/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9245 - loss: 0.2088 - val_accuracy: 0.9659 - val_loss: 0.0944
Epoch 33/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9251 - loss: 0.2022 - val_accuracy: 0.9735 - val_loss: 0.0898
Epoch 34/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9211 - loss: 0.2195 - val_accuracy: 0.9735 - val_loss: 0.0792
Epoch 35/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9285 - loss: 0.1901 - val_accuracy: 0.9735 - val_loss: 0.0838
Epoch 36/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9231 - loss: 0.2015 - val_accuracy: 0.9697 - val_loss: 0.0838
Epoch 37/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9251 - loss: 0.1859 - val_accuracy: 0.9735 - val_loss: 0.0843
Epoch 38/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9352 - loss: 0.1864 - val_accuracy: 0.9659 - val_loss: 0.0830
Epoch 39/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9265 - loss: 0.1912 - val_accuracy: 0.9659 - val_loss: 0.0813
Epoch 40/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9332 - loss: 0.1853 - val_accuracy: 0.9697 - val_loss: 0.0763
Epoch 41/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9251 - loss: 0.1875 - val_accuracy: 0.9697 - val_loss: 0.0808
Epoch 42/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9325 - loss: 0.1776 - val_accuracy: 0.9735 - val_loss: 0.0774
Epoch 43/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9392 - loss: 0.1658 - val_accuracy: 0.9773 - val_loss: 0.0738
Epoch 44/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9499 - loss: 0.1468 - val_accuracy: 0.9735 - val_loss: 0.0805
Epoch 45/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9398 - loss: 0.1622 - val_accuracy: 0.9697 - val_loss: 0.0799
Epoch 46/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9392 - loss: 0.1574 - val_accuracy: 0.9735 - val_loss: 0.0775
Epoch 47/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9465 - loss: 0.1469 - val_accuracy: 0.9773 - val_loss: 0.0697
Epoch 48/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9398 - loss: 0.1543 - val_accuracy: 0.9773 - val_loss: 0.0695
Epoch 49/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9392 - loss: 0.1560 - val_accuracy: 0.9735 - val_loss: 0.0697
Epoch 50/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9412 - loss: 0.1599 - val_accuracy: 0.9735 - val_loss: 0.0669
Epoch 51/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9325 - loss: 0.1607 - val_accuracy: 0.9735 - val_loss: 0.0707
Epoch 52/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9545 - loss: 0.1358 - val_accuracy: 0.9697 - val_loss: 0.0692
Epoch 53/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9452 - loss: 0.1416 - val_accuracy: 0.9773 - val_loss: 0.0608
Epoch 54/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9398 - loss: 0.1525 - val_accuracy: 0.9735 - val_loss: 0.0658
Epoch 55/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9452 - loss: 0.1482 - val_accuracy: 0.9735 - val_loss: 0.0621
Epoch 56/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9479 - loss: 0.1472 - val_accuracy: 0.9735 - val_loss: 0.0647
Epoch 57/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9439 - loss: 0.1509 - val_accuracy: 0.9735 - val_loss: 0.0636
Epoch 58/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9505 - loss: 0.1387 - val_accuracy: 0.9735 - val_loss: 0.0631
Epoch 59/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9385 - loss: 0.1583 - val_accuracy: 0.9773 - val_loss: 0.0598
Epoch 60/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9519 - loss: 0.1319 - val_accuracy: 0.9811 - val_loss: 0.0604
Epoch 61/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9492 - loss: 0.1323 - val_accuracy: 0.9735 - val_loss: 0.0571
Epoch 62/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9559 - loss: 0.1261 - val_accuracy: 0.9735 - val_loss: 0.0600
Epoch 63/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9505 - loss: 0.1292 - val_accuracy: 0.9773 - val_loss: 0.0568
Epoch 64/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9452 - loss: 0.1408 - val_accuracy: 0.9811 - val_loss: 0.0554
Epoch 65/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9539 - loss: 0.1124 - val_accuracy: 0.9735 - val_loss: 0.0561
Epoch 66/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9505 - loss: 0.1372 - val_accuracy: 0.9735 - val_loss: 0.0573
Epoch 67/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9525 - loss: 0.1214 - val_accuracy: 0.9735 - val_loss: 0.0604
Epoch 68/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9505 - loss: 0.1255 - val_accuracy: 0.9697 - val_loss: 0.0603
Epoch 69/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9459 - loss: 0.1289 - val_accuracy: 0.9735 - val_loss: 0.0589
Epoch 70/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9552 - loss: 0.1226 - val_accuracy: 0.9773 - val_loss: 0.0608
Epoch 71/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9612 - loss: 0.1084 - val_accuracy: 0.9735 - val_loss: 0.0600
Epoch 72/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9566 - loss: 0.1187 - val_accuracy: 0.9697 - val_loss: 0.0591
Epoch 73/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9586 - loss: 0.1110 - val_accuracy: 0.9811 - val_loss: 0.0495
Epoch 74/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9599 - loss: 0.1122 - val_accuracy: 0.9735 - val_loss: 0.0566
Epoch 75/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9592 - loss: 0.1244 - val_accuracy: 0.9773 - val_loss: 0.0483
Epoch 76/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9619 - loss: 0.1158 - val_accuracy: 0.9773 - val_loss: 0.0502
Epoch 77/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9626 - loss: 0.1041 - val_accuracy: 0.9811 - val_loss: 0.0524
Epoch 78/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9545 - loss: 0.1186 - val_accuracy: 0.9773 - val_loss: 0.0510
Epoch 79/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9652 - loss: 0.0904 - val_accuracy: 0.9773 - val_loss: 0.0499
Epoch 80/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9579 - loss: 0.1101 - val_accuracy: 0.9735 - val_loss: 0.0542
Epoch 81/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9592 - loss: 0.0984 - val_accuracy: 0.9735 - val_loss: 0.0546
Epoch 82/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9619 - loss: 0.1004 - val_accuracy: 0.9773 - val_loss: 0.0542
Epoch 83/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9612 - loss: 0.1076 - val_accuracy: 0.9735 - val_loss: 0.0518
Epoch 84/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9606 - loss: 0.0974 - val_accuracy: 0.9811 - val_loss: 0.0488
Epoch 85/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9606 - loss: 0.1079 - val_accuracy: 0.9811 - val_loss: 0.0508

In [5]:
y_pred_a_probs = model_a.predict(X_test_a_scaled)
y_pred_a = np.argmax(y_pred_a_probs, axis=1)

print("Test Accuracy:", accuracy_score(y_test_a, y_pred_a))
print("Test F1 (macro):", f1_score(y_test_a, y_pred_a, average='macro'))
print(classification_report(y_test_a, y_pred_a, target_names=le.classes_))

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Test Accuracy: 0.990909090909091
Test F1 (macro): 0.9909062482233214
              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        20
      banana       1.00      1.00      1.00        20
   blackgram       1.00      1.00      1.00        20
    chickpea       1.00      1.00      1.00        20
     coconut       1.00      1.00      1.00        20
      coffee       1.00      1.00      1.00        20
      cotton       0.95      1.00      0.98        20
      grapes       1.00      1.00      1.00        20
        jute       0.95      0.95      0.95        20
 kidneybeans       1.00      1.00      1.00        20
      lentil       1.00      1.00      1.00        20
       maize       1.00      0.95      0.97        20
       mango       1.00      1.00      1.00        20
   mothbeans       1.00      1.00      1.00        20
    mungbean       1.00      1.00      1.00        20
   muskmelon       0.95      1.00      0.98        20
      orange       1.00      1.00      1.00        20
      papaya       1.00      1.00      1.00        20
  pigeonpeas       1.00      1.00      1.00        20
 pomegranate       1.00      1.00      1.00        20
        rice       0.95      0.95      0.95        20
  watermelon       1.00      0.95      0.97        20

    accuracy                           0.99       440
   macro avg       0.99      0.99      0.99       440
weighted avg       0.99      0.99      0.99       440

In [6]:
import os
os.makedirs("../src/models/saved", exist_ok=True)

model_a.save("../src/models/saved/model_a_crop_recommendation.keras")
print("Model A saved")

# also save the scaler and label encoder — needed at inference time
import joblib
joblib.dump(scaler_a, "../src/models/saved/scaler_a.pkl")
joblib.dump(le, "../src/models/saved/label_encoder_a.pkl")
print("Scaler and label encoder saved")

Model A saved
Scaler and label encoder saved

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

df_b = pd.read_csv("../data/processed/model_b_training_data.csv")
df_b_encoded = pd.get_dummies(df_b, columns=['state_name', 'crop', 'season'], drop_first=True)

X_b = df_b_encoded.drop(columns=['yield_kg_per_ha']).astype(float)
y_b = df_b_encoded['yield_kg_per_ha'].astype(float)

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X_b, y_b, test_size=0.2, random_state=42
)

scaler_b = StandardScaler()
X_train_b_scaled = scaler_b.fit_transform(X_train_b)
X_test_b_scaled = scaler_b.transform(X_test_b)

print(X_train_b_scaled.shape, X_test_b_scaled.shape)

(26614, 29) (6654, 29)

In [2]:
model_b = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train_b_scaled.shape[1],)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)
])

model_b.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

model_b.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │           3,840 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14,209 (55.50 KB)

 Trainable params: 14,209 (55.50 KB)

 Non-trainable params: 0 (0.00 B)

In [3]:
history_b = model_b.fit(
    X_train_b_scaled, y_train_b,
    validation_split=0.15,
    epochs=100,
    batch_size=64,
    verbose=1,
    callbacks=[tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)]
)

Epoch 1/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 1177955.7500 - mae: 728.8232 - val_loss: 463087.0625 - val_mae: 457.8084
Epoch 2/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 470247.2812 - mae: 454.7132 - val_loss: 408812.5000 - val_mae: 417.3432
Epoch 3/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 430451.9688 - mae: 428.8354 - val_loss: 385701.3125 - val_mae: 399.0197
Epoch 4/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 415959.2812 - mae: 417.0376 - val_loss: 378834.9688 - val_mae: 391.1928
Epoch 5/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 410208.7500 - mae: 413.5878 - val_loss: 370540.6250 - val_mae: 386.2433
Epoch 6/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 403879.4688 - mae: 407.2546 - val_loss: 368999.9688 - val_mae: 389.1732
Epoch 7/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 402960.0938 - mae: 405.5617 - val_loss: 365121.6875 - val_mae: 381.5890
Epoch 8/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 394473.5000 - mae: 403.3962 - val_loss: 361443.5312 - val_mae: 382.6227
Epoch 9/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 394299.9375 - mae: 402.4543 - val_loss: 360688.3750 - val_mae: 380.5001
Epoch 10/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 388402.5625 - mae: 399.2828 - val_loss: 359466.2500 - val_mae: 382.1711
Epoch 11/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 388460.4375 - mae: 399.5892 - val_loss: 357184.7812 - val_mae: 380.4091
Epoch 12/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 388429.2188 - mae: 399.1914 - val_loss: 359016.5625 - val_mae: 376.2590
Epoch 13/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 385230.5000 - mae: 395.8561 - val_loss: 355678.8125 - val_mae: 377.8052
Epoch 14/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 385037.0938 - mae: 396.7702 - val_loss: 353443.8438 - val_mae: 377.4764
Epoch 15/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 383377.7188 - mae: 396.5746 - val_loss: 351733.3750 - val_mae: 375.5264
Epoch 16/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 379052.8750 - mae: 393.0797 - val_loss: 350895.0312 - val_mae: 376.7314
Epoch 17/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 378248.7500 - mae: 393.7569 - val_loss: 352549.3125 - val_mae: 379.4888
Epoch 18/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 375137.8750 - mae: 391.9885 - val_loss: 351009.2188 - val_mae: 379.5260
Epoch 19/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 380102.0000 - mae: 392.3568 - val_loss: 348528.0938 - val_mae: 373.3315
Epoch 20/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 380469.2188 - mae: 392.6613 - val_loss: 350779.8438 - val_mae: 381.1629
Epoch 21/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 374997.8750 - mae: 391.1442 - val_loss: 348393.6250 - val_mae: 370.1288
Epoch 22/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 369710.0000 - mae: 389.0450 - val_loss: 345556.8750 - val_mae: 373.0524
Epoch 23/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 373320.9375 - mae: 390.8024 - val_loss: 346723.6250 - val_mae: 369.0282
Epoch 24/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 376304.6875 - mae: 389.4021 - val_loss: 343682.9062 - val_mae: 368.6420
Epoch 25/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 372141.9375 - mae: 390.3585 - val_loss: 345384.4062 - val_mae: 369.9149
Epoch 26/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 370398.1875 - mae: 388.3070 - val_loss: 344842.3750 - val_mae: 367.1918
Epoch 27/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 369773.6875 - mae: 387.2271 - val_loss: 343940.0312 - val_mae: 368.4710
Epoch 28/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 368756.3750 - mae: 388.0715 - val_loss: 341036.6562 - val_mae: 368.6375
Epoch 29/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 366441.4375 - mae: 386.1137 - val_loss: 341716.2188 - val_mae: 372.5181
Epoch 30/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 371381.7812 - mae: 389.6394 - val_loss: 351717.5000 - val_mae: 367.5621
Epoch 31/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 366556.8750 - mae: 386.4439 - val_loss: 338944.6562 - val_mae: 370.1647
Epoch 32/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 362031.5938 - mae: 384.2127 - val_loss: 339719.0312 - val_mae: 366.0736
Epoch 33/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 364875.7188 - mae: 385.3017 - val_loss: 337981.7500 - val_mae: 364.7487
Epoch 34/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 362329.2500 - mae: 383.5173 - val_loss: 336082.6875 - val_mae: 364.4327
Epoch 35/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 361595.8438 - mae: 385.9859 - val_loss: 333758.6250 - val_mae: 365.2982
Epoch 36/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 362090.0938 - mae: 382.6918 - val_loss: 334488.0000 - val_mae: 366.9191
Epoch 37/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 359647.1562 - mae: 382.7555 - val_loss: 334644.4062 - val_mae: 367.1602
Epoch 38/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 359011.0312 - mae: 382.9028 - val_loss: 334187.6875 - val_mae: 363.6861
Epoch 39/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 359505.4062 - mae: 382.7794 - val_loss: 332662.2188 - val_mae: 362.8882
Epoch 40/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 357272.7812 - mae: 382.4015 - val_loss: 333670.6562 - val_mae: 361.7975
Epoch 41/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 356104.0312 - mae: 381.1826 - val_loss: 331693.6562 - val_mae: 361.6066
Epoch 42/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 356867.9688 - mae: 382.6526 - val_loss: 335661.0312 - val_mae: 361.8923
Epoch 43/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 353716.3438 - mae: 380.2571 - val_loss: 330438.1562 - val_mae: 364.1580
Epoch 44/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 353636.6562 - mae: 380.9242 - val_loss: 330256.2812 - val_mae: 361.0003
Epoch 45/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 353163.7188 - mae: 379.5984 - val_loss: 327106.2500 - val_mae: 360.1120
Epoch 46/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 356640.9688 - mae: 379.9258 - val_loss: 328196.4062 - val_mae: 361.3633
Epoch 47/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 350147.3438 - mae: 378.8942 - val_loss: 328354.7812 - val_mae: 360.3592
Epoch 48/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 351377.4375 - mae: 379.7505 - val_loss: 331781.1562 - val_mae: 359.0380
Epoch 49/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 353560.3750 - mae: 379.7498 - val_loss: 327090.7500 - val_mae: 362.9165
Epoch 50/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 350866.9062 - mae: 378.7383 - val_loss: 329129.1562 - val_mae: 361.8282
Epoch 51/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 353574.4375 - mae: 378.9357 - val_loss: 325547.2812 - val_mae: 362.5422
Epoch 52/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 349696.8438 - mae: 377.6208 - val_loss: 327428.2500 - val_mae: 364.1761
Epoch 53/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 349133.6250 - mae: 378.4157 - val_loss: 328320.8438 - val_mae: 359.7475
Epoch 54/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 352008.1250 - mae: 377.6266 - val_loss: 327624.8438 - val_mae: 358.8086
Epoch 55/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 349293.7188 - mae: 377.2333 - val_loss: 325332.7812 - val_mae: 356.6902
Epoch 56/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 347929.1875 - mae: 377.2863 - val_loss: 326982.1250 - val_mae: 364.8269
Epoch 57/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 347130.1875 - mae: 376.6664 - val_loss: 329530.8750 - val_mae: 361.2158
Epoch 58/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 348100.0000 - mae: 377.7005 - val_loss: 324169.5312 - val_mae: 358.7092
Epoch 59/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 340516.8125 - mae: 374.7522 - val_loss: 322537.8125 - val_mae: 357.7747
Epoch 60/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 349261.2500 - mae: 377.2312 - val_loss: 324157.6875 - val_mae: 356.3766
Epoch 61/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 353653.8750 - mae: 378.6273 - val_loss: 326644.1250 - val_mae: 358.1612
Epoch 62/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 354712.5312 - mae: 378.8417 - val_loss: 324874.7188 - val_mae: 358.2527
Epoch 63/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 348951.6562 - mae: 376.1839 - val_loss: 324229.0938 - val_mae: 361.9009
Epoch 64/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 348513.7188 - mae: 377.5672 - val_loss: 323496.4062 - val_mae: 356.7429
Epoch 65/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 344809.4375 - mae: 375.9650 - val_loss: 321593.2188 - val_mae: 357.7206
Epoch 66/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 347671.1875 - mae: 377.7024 - val_loss: 321261.9062 - val_mae: 356.9936
Epoch 67/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 347057.0625 - mae: 376.4188 - val_loss: 326162.7812 - val_mae: 357.4294
Epoch 68/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 346562.2812 - mae: 374.6521 - val_loss: 320555.7500 - val_mae: 358.4018
Epoch 69/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 345741.5000 - mae: 376.1203 - val_loss: 322578.3750 - val_mae: 360.1016
Epoch 70/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 347482.5312 - mae: 376.3414 - val_loss: 322086.2500 - val_mae: 357.2624
Epoch 71/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 343838.5625 - mae: 375.5703 - val_loss: 320038.0938 - val_mae: 355.6846
Epoch 72/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 341644.3438 - mae: 375.8561 - val_loss: 320194.1250 - val_mae: 355.9662
Epoch 73/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 345165.6562 - mae: 376.3484 - val_loss: 320150.6562 - val_mae: 354.6243
Epoch 74/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 342238.0625 - mae: 375.4115 - val_loss: 322691.6562 - val_mae: 356.1544
Epoch 75/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 345025.4062 - mae: 374.3391 - val_loss: 319663.2500 - val_mae: 359.9509
Epoch 76/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 343518.4688 - mae: 373.6524 - val_loss: 318152.0312 - val_mae: 357.0535
Epoch 77/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 349727.9375 - mae: 377.3167 - val_loss: 319472.3125 - val_mae: 356.0541
Epoch 78/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 346165.3125 - mae: 375.0331 - val_loss: 319179.5938 - val_mae: 355.5822
Epoch 79/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 344186.4062 - mae: 374.9294 - val_loss: 319572.2500 - val_mae: 355.5016
Epoch 80/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 340231.4375 - mae: 374.9220 - val_loss: 319215.4375 - val_mae: 356.4763
Epoch 81/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 343721.1562 - mae: 374.9108 - val_loss: 317076.4062 - val_mae: 354.0117
Epoch 82/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 342802.5625 - mae: 374.8032 - val_loss: 318222.9062 - val_mae: 354.6544
Epoch 83/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 341723.3125 - mae: 374.4919 - val_loss: 319917.2812 - val_mae: 355.0720
Epoch 84/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 340615.9688 - mae: 373.6370 - val_loss: 326064.6562 - val_mae: 357.2988
Epoch 85/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 340767.9688 - mae: 374.6501 - val_loss: 321287.3125 - val_mae: 356.4699
Epoch 86/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 342373.9688 - mae: 374.6638 - val_loss: 319019.6250 - val_mae: 357.2913
Epoch 87/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 339680.6562 - mae: 374.3950 - val_loss: 316357.8125 - val_mae: 353.8522
Epoch 88/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 343869.2812 - mae: 374.6958 - val_loss: 314562.5625 - val_mae: 352.6299
Epoch 89/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 341805.2188 - mae: 374.9997 - val_loss: 318485.8125 - val_mae: 355.9825
Epoch 90/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 342310.1875 - mae: 372.3631 - val_loss: 318560.9688 - val_mae: 354.9752
Epoch 91/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 340422.1562 - mae: 374.0469 - val_loss: 316307.8750 - val_mae: 357.8060
Epoch 92/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 337568.8125 - mae: 372.2344 - val_loss: 315848.4375 - val_mae: 352.1885
Epoch 93/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 344192.3125 - mae: 373.0983 - val_loss: 316026.5312 - val_mae: 352.2536
Epoch 94/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 341425.4062 - mae: 373.8691 - val_loss: 314106.5938 - val_mae: 355.3363
Epoch 95/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 340979.2500 - mae: 372.7154 - val_loss: 315127.6562 - val_mae: 353.2039
Epoch 96/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 343871.0625 - mae: 374.3198 - val_loss: 316337.6250 - val_mae: 357.2927
Epoch 97/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 336340.1562 - mae: 371.0142 - val_loss: 312488.4375 - val_mae: 355.4115
Epoch 98/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 338292.3125 - mae: 373.1039 - val_loss: 320033.0000 - val_mae: 354.7905
Epoch 99/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 341500.0000 - mae: 373.3725 - val_loss: 317385.3125 - val_mae: 354.4864
Epoch 100/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 340839.9375 - mae: 373.4369 - val_loss: 317476.4062 - val_mae: 356.4405

In [4]:
y_pred_b = model_b.predict(X_test_b_scaled).flatten()
rmse_b = np.sqrt(mean_squared_error(y_test_b, y_pred_b))
r2_b = r2_score(y_test_b, y_pred_b)
print("Test RMSE:", rmse_b)
print("Test R²:", r2_b)

208/208 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step
Test RMSE: 587.7860825741176
Test R²: 0.6983544076957906

In [5]:
y_train_b_log = np.log1p(y_train_b)
y_test_b_log = np.log1p(y_test_b)

model_b_log = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train_b_scaled.shape[1],)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)
])

model_b_log.compile(optimizer='adam', loss='mse', metrics=['mae'])

history_b_log = model_b_log.fit(
    X_train_b_scaled, y_train_b_log,
    validation_split=0.15,
    epochs=100,
    batch_size=64,
    verbose=1,
    callbacks=[tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)]
)

Epoch 1/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 3.2857 - mae: 1.2561 - val_loss: 0.3435 - val_mae: 0.4600
Epoch 2/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9244 - mae: 0.7609 - val_loss: 0.4035 - val_mae: 0.5262
Epoch 3/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6960 - mae: 0.6556 - val_loss: 0.4474 - val_mae: 0.5644
Epoch 4/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5596 - mae: 0.5848 - val_loss: 0.7232 - val_mae: 0.7546
Epoch 5/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4709 - mae: 0.5345 - val_loss: 0.9385 - val_mae: 0.8766
Epoch 6/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3942 - mae: 0.4842 - val_loss: 1.3374 - val_mae: 1.0653
Epoch 7/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3510 - mae: 0.4537 - val_loss: 1.0785 - val_mae: 0.9480
Epoch 8/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3206 - mae: 0.4322 - val_loss: 1.0732 - val_mae: 0.9462
Epoch 9/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2919 - mae: 0.4086 - val_loss: 0.9908 - val_mae: 0.9042
Epoch 10/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2769 - mae: 0.3963 - val_loss: 0.9048 - val_mae: 0.8571
Epoch 11/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2639 - mae: 0.3850 - val_loss: 0.8775 - val_mae: 0.8435

In [6]:
y_pred_log = model_b_log.predict(X_test_b_scaled).flatten()
y_pred_b_final = np.expm1(y_pred_log)

rmse_log = np.sqrt(mean_squared_error(y_test_b, y_pred_b_final))
r2_log = r2_score(y_test_b, y_pred_b_final)
print("Test RMSE (log-transformed target):", rmse_log)
print("Test R² (log-transformed target):", r2_log)

208/208 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step
Test RMSE (log-transformed target): 907.2001346135227
Test R² (log-transformed target): 0.2814374181502409

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score

df_b = pd.read_csv("../data/processed/model_b_training_data.csv")

# Label encode categoricals (embeddings need integer indices, not one-hot)
le_state = LabelEncoder()
le_crop = LabelEncoder()
le_season = LabelEncoder()

df_b['state_idx'] = le_state.fit_transform(df_b['state_name'])
df_b['crop_idx'] = le_crop.fit_transform(df_b['crop'])
df_b['season_idx'] = le_season.fit_transform(df_b['season'])

print("States:", len(le_state.classes_))
print("Crops:", len(le_crop.classes_))
print("Seasons:", len(le_season.classes_))

States: 20
Crops: 4
Seasons: 2

In [2]:
numeric_cols = ['area_ha', 'temperature_c', 'humidity_pct', 'rainfall_mm', 
                 'wind_speed_m_s', 'solar_radiation_mj_m2_day']

X_numeric = df_b[numeric_cols].values
X_state = df_b['state_idx'].values
X_crop = df_b['crop_idx'].values
X_season = df_b['season_idx'].values
y = df_b['yield_kg_per_ha'].values

# split all arrays together using the same indices
indices = np.arange(len(df_b))
train_idx, test_idx = train_test_split(indices, test_size=0.2, random_state=42)

X_num_train, X_num_test = X_numeric[train_idx], X_numeric[test_idx]
X_state_train, X_state_test = X_state[train_idx], X_state[test_idx]
X_crop_train, X_crop_test = X_crop[train_idx], X_crop[test_idx]
X_season_train, X_season_test = X_season[train_idx], X_season[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

# scale only numeric features
scaler = StandardScaler()
X_num_train_scaled = scaler.fit_transform(X_num_train)
X_num_test_scaled = scaler.transform(X_num_test)

print(X_num_train_scaled.shape, X_state_train.shape, X_crop_train.shape, X_season_train.shape)

(26614, 6) (26614,) (26614,) (26614,)

In [3]:
# Embedding dimension: a common rule of thumb is min(50, (num_categories+1)//2)
state_emb_dim = min(10, (20+1)//2)  # 10
crop_emb_dim = min(4, (4+1)//2)      # 2
season_emb_dim = 2                    # only 2 categories, keep it small

# Inputs
numeric_input = tf.keras.layers.Input(shape=(6,), name='numeric_input')
state_input = tf.keras.layers.Input(shape=(1,), name='state_input')
crop_input = tf.keras.layers.Input(shape=(1,), name='crop_input')
season_input = tf.keras.layers.Input(shape=(1,), name='season_input')

# Embeddings
state_emb = tf.keras.layers.Embedding(input_dim=20, output_dim=state_emb_dim)(state_input)
state_emb = tf.keras.layers.Flatten()(state_emb)

crop_emb = tf.keras.layers.Embedding(input_dim=4, output_dim=crop_emb_dim)(crop_input)
crop_emb = tf.keras.layers.Flatten()(crop_emb)

season_emb = tf.keras.layers.Embedding(input_dim=2, output_dim=season_emb_dim)(season_input)
season_emb = tf.keras.layers.Flatten()(season_emb)

# Concatenate everything
concat = tf.keras.layers.Concatenate()([numeric_input, state_emb, crop_emb, season_emb])

# Dense layers
x = tf.keras.layers.Dense(128, activation='relu')(concat)
x = tf.keras.layers.Dropout(0.3)(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(32, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_b_emb = tf.keras.Model(
    inputs=[numeric_input, state_input, crop_input, season_input],
    outputs=output
)

model_b_emb.compile(optimizer='adam', loss='mse', metrics=['mae'])
model_b_emb.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ state_input (InputLayer)      │ (None, 1)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ crop_input (InputLayer)       │ (None, 1)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ season_input (InputLayer)     │ (None, 1)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ embedding (Embedding)         │ (None, 1, 10)             │             200 │ state_input[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ embedding_1 (Embedding)       │ (None, 1, 2)              │               8 │ crop_input[0][0]           │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ embedding_2 (Embedding)       │ (None, 1, 2)              │               4 │ season_input[0][0]         │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ numeric_input (InputLayer)    │ (None, 6)                 │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ flatten (Flatten)             │ (None, 10)                │               0 │ embedding[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ flatten_1 (Flatten)           │ (None, 2)                 │               0 │ embedding_1[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ flatten_2 (Flatten)           │ (None, 2)                 │               0 │ embedding_2[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ concatenate (Concatenate)     │ (None, 20)                │               0 │ numeric_input[0][0],       │
│                               │                           │                 │ flatten[0][0],             │
│                               │                           │                 │ flatten_1[0][0],           │
│                               │                           │                 │ flatten_2[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense (Dense)                 │ (None, 128)               │           2,688 │ concatenate[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout (Dropout)             │ (None, 128)               │               0 │ dense[0][0]                │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_1 (Dense)               │ (None, 64)                │           8,256 │ dropout[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dropout_1 (Dropout)           │ (None, 64)                │               0 │ dense_1[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_2 (Dense)               │ (None, 32)                │           2,080 │ dropout_1[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_3 (Dense)               │ (None, 1)                 │              33 │ dense_2[0][0]              │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 13,269 (51.83 KB)

 Trainable params: 13,269 (51.83 KB)

 Non-trainable params: 0 (0.00 B)

In [4]:
history_b_emb = model_b_emb.fit(
    [X_num_train_scaled, X_state_train, X_crop_train, X_season_train],
    y_train,
    validation_split=0.15,
    epochs=100,
    batch_size=64,
    verbose=1,
    callbacks=[tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)]
)

Epoch 1/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - loss: 1247387.0000 - mae: 779.5645 - val_loss: 529807.0000 - val_mae: 504.8012
Epoch 2/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 525473.6250 - mae: 504.1162 - val_loss: 483565.1562 - val_mae: 487.8602
Epoch 3/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 508038.4062 - mae: 494.4444 - val_loss: 476126.4062 - val_mae: 476.5057
Epoch 4/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 503272.9062 - mae: 488.5712 - val_loss: 470051.9375 - val_mae: 479.9327
Epoch 5/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 493570.1875 - mae: 482.9403 - val_loss: 457959.5312 - val_mae: 468.4350
Epoch 6/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 485990.0938 - mae: 478.5378 - val_loss: 449847.2188 - val_mae: 458.9201
Epoch 7/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 475942.6562 - mae: 472.0465 - val_loss: 434700.2812 - val_mae: 447.8304
Epoch 8/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 456382.9688 - mae: 458.5849 - val_loss: 419977.3438 - val_mae: 435.7561
Epoch 9/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 445317.8125 - mae: 445.1989 - val_loss: 416300.4062 - val_mae: 422.7781
Epoch 10/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 440021.8750 - mae: 439.8764 - val_loss: 406537.9062 - val_mae: 416.8151
Epoch 11/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 433089.0000 - mae: 433.8713 - val_loss: 402658.5312 - val_mae: 414.8561
Epoch 12/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 432214.8750 - mae: 433.3745 - val_loss: 401829.1250 - val_mae: 412.7773
Epoch 13/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 431293.7500 - mae: 431.3545 - val_loss: 400242.0000 - val_mae: 416.4499
Epoch 14/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 431691.0312 - mae: 431.5394 - val_loss: 397560.0625 - val_mae: 411.2750
Epoch 15/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 428075.5000 - mae: 429.5782 - val_loss: 401328.0938 - val_mae: 408.9034
Epoch 16/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 428439.9375 - mae: 427.4517 - val_loss: 394758.4688 - val_mae: 407.9301
Epoch 17/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 427045.4375 - mae: 427.0303 - val_loss: 394168.8125 - val_mae: 406.4539
Epoch 18/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 423514.0625 - mae: 426.0743 - val_loss: 393964.6562 - val_mae: 405.6937
Epoch 19/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 425988.8438 - mae: 426.0667 - val_loss: 388864.3125 - val_mae: 407.4818
Epoch 20/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 420985.5312 - mae: 423.7039 - val_loss: 388374.0938 - val_mae: 404.5789
Epoch 21/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 423713.3750 - mae: 424.7095 - val_loss: 389134.6562 - val_mae: 403.0867
Epoch 22/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 422882.9688 - mae: 423.1411 - val_loss: 385334.7188 - val_mae: 401.1165
Epoch 23/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 421529.8125 - mae: 423.0680 - val_loss: 387256.0938 - val_mae: 402.8423
Epoch 24/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 418828.6250 - mae: 423.0414 - val_loss: 383084.1250 - val_mae: 403.2621
Epoch 25/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 415178.9375 - mae: 420.6615 - val_loss: 382664.0938 - val_mae: 403.2143
Epoch 26/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 411244.0625 - mae: 418.6654 - val_loss: 380006.1562 - val_mae: 398.0768
Epoch 27/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 415051.0938 - mae: 418.9162 - val_loss: 381246.0938 - val_mae: 398.7816
Epoch 28/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 411188.8438 - mae: 418.2632 - val_loss: 377040.6250 - val_mae: 396.9142
Epoch 29/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 409027.1875 - mae: 416.7801 - val_loss: 375677.5000 - val_mae: 395.3640
Epoch 30/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 409757.6250 - mae: 415.6570 - val_loss: 372879.2500 - val_mae: 395.5456
Epoch 31/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 408251.8438 - mae: 415.6760 - val_loss: 370176.5312 - val_mae: 391.4843
Epoch 32/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 409692.4062 - mae: 414.8461 - val_loss: 371406.9688 - val_mae: 390.6057
Epoch 33/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 402350.3438 - mae: 413.1378 - val_loss: 372047.3125 - val_mae: 395.5100
Epoch 34/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 404180.8125 - mae: 412.7101 - val_loss: 378070.6875 - val_mae: 391.1419
Epoch 35/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 399290.0312 - mae: 411.3239 - val_loss: 367956.8125 - val_mae: 391.1741
Epoch 36/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 399445.8125 - mae: 411.8683 - val_loss: 365960.5000 - val_mae: 389.0224
Epoch 37/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 398138.4375 - mae: 409.8598 - val_loss: 365595.7812 - val_mae: 389.0702
Epoch 38/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 397850.9062 - mae: 409.0466 - val_loss: 364348.1250 - val_mae: 388.7750
Epoch 39/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 396473.1875 - mae: 408.8727 - val_loss: 363792.3125 - val_mae: 388.2084
Epoch 40/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 397012.8750 - mae: 408.5623 - val_loss: 363811.3438 - val_mae: 388.2487
Epoch 41/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 394512.4062 - mae: 407.5794 - val_loss: 361878.3125 - val_mae: 389.7320
Epoch 42/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 394382.9688 - mae: 409.0047 - val_loss: 362907.6562 - val_mae: 393.2599
Epoch 43/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 393427.3438 - mae: 407.6701 - val_loss: 361234.1875 - val_mae: 386.8883
Epoch 44/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 391172.8750 - mae: 405.7761 - val_loss: 366658.4062 - val_mae: 387.2454
Epoch 45/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 390905.2812 - mae: 407.6776 - val_loss: 364589.0312 - val_mae: 384.9786
Epoch 46/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 389785.7188 - mae: 405.2293 - val_loss: 358603.5000 - val_mae: 385.4188
Epoch 47/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 392314.4375 - mae: 405.1878 - val_loss: 357544.0938 - val_mae: 386.7722
Epoch 48/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 387421.8438 - mae: 405.2340 - val_loss: 357330.5312 - val_mae: 383.6027
Epoch 49/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 385316.7500 - mae: 403.0878 - val_loss: 355051.6250 - val_mae: 382.2384
Epoch 50/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 387222.1875 - mae: 403.0510 - val_loss: 353205.6250 - val_mae: 383.4557
Epoch 51/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 387335.1562 - mae: 402.8651 - val_loss: 352467.1562 - val_mae: 382.4186
Epoch 52/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 383136.4688 - mae: 401.1866 - val_loss: 349842.7812 - val_mae: 381.2949
Epoch 53/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 381359.0000 - mae: 400.8251 - val_loss: 351550.2188 - val_mae: 381.5840
Epoch 54/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 382571.6562 - mae: 399.9023 - val_loss: 351133.2812 - val_mae: 380.3400
Epoch 55/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 383132.6562 - mae: 400.3983 - val_loss: 349649.9375 - val_mae: 378.2831
Epoch 56/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 380258.0312 - mae: 400.2286 - val_loss: 349357.6875 - val_mae: 376.5671
Epoch 57/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 382543.6562 - mae: 399.9117 - val_loss: 352330.0000 - val_mae: 377.6543
Epoch 58/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 380276.6562 - mae: 398.3809 - val_loss: 349362.9688 - val_mae: 382.5849
Epoch 59/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 375161.1562 - mae: 397.9393 - val_loss: 346186.2812 - val_mae: 379.1180
Epoch 60/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 379464.1875 - mae: 398.1817 - val_loss: 346040.4688 - val_mae: 378.4689
Epoch 61/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 378787.0938 - mae: 397.6646 - val_loss: 348896.6562 - val_mae: 381.0753
Epoch 62/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 379856.1562 - mae: 399.2812 - val_loss: 344963.2812 - val_mae: 378.4312
Epoch 63/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 376762.1875 - mae: 397.0245 - val_loss: 345549.3438 - val_mae: 377.9116
Epoch 64/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 372075.7500 - mae: 394.2063 - val_loss: 346012.2500 - val_mae: 375.8782
Epoch 65/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 373484.7188 - mae: 395.5284 - val_loss: 343776.0625 - val_mae: 375.1209
Epoch 66/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 373522.0938 - mae: 395.4655 - val_loss: 344950.1250 - val_mae: 380.7341
Epoch 67/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 371859.7500 - mae: 393.4759 - val_loss: 341194.8125 - val_mae: 372.7272
Epoch 68/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 377241.6875 - mae: 396.1015 - val_loss: 344242.4375 - val_mae: 373.9608
Epoch 69/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 361330.1875 - mae: 389.8566 - val_loss: 338449.2188 - val_mae: 374.5444
Epoch 70/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 367568.8750 - mae: 391.7524 - val_loss: 342906.1875 - val_mae: 372.8148
Epoch 71/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 371697.0312 - mae: 391.9361 - val_loss: 336870.4375 - val_mae: 373.4134
Epoch 72/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 364624.3125 - mae: 391.9939 - val_loss: 339198.0312 - val_mae: 371.0499
Epoch 73/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 365194.4062 - mae: 389.9537 - val_loss: 340783.7188 - val_mae: 377.9200
Epoch 74/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 370151.4688 - mae: 392.4763 - val_loss: 339995.4688 - val_mae: 371.2104
Epoch 75/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 364914.6875 - mae: 390.2329 - val_loss: 336155.4062 - val_mae: 369.9471
Epoch 76/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 366885.8125 - mae: 390.3846 - val_loss: 339531.6250 - val_mae: 374.9962
Epoch 77/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 367145.9062 - mae: 390.4589 - val_loss: 334823.9375 - val_mae: 369.5328
Epoch 78/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 365784.0312 - mae: 390.1247 - val_loss: 330838.4062 - val_mae: 372.1469
Epoch 79/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 359836.6562 - mae: 387.4396 - val_loss: 332190.8750 - val_mae: 368.4784
Epoch 80/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 364159.1250 - mae: 389.7244 - val_loss: 332296.0938 - val_mae: 367.9054
Epoch 81/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 358287.0312 - mae: 387.3450 - val_loss: 332329.1562 - val_mae: 367.2832
Epoch 82/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 358881.3438 - mae: 386.8393 - val_loss: 331464.9062 - val_mae: 367.8419
Epoch 83/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 360634.3750 - mae: 387.0889 - val_loss: 329229.8750 - val_mae: 365.6337
Epoch 84/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 361570.9375 - mae: 386.5039 - val_loss: 329243.4375 - val_mae: 367.9669
Epoch 85/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 356042.2500 - mae: 384.7719 - val_loss: 326257.4688 - val_mae: 367.7571
Epoch 86/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 357892.2500 - mae: 386.1122 - val_loss: 324570.7188 - val_mae: 365.6931
Epoch 87/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 357571.5938 - mae: 385.2646 - val_loss: 323352.8438 - val_mae: 363.7713
Epoch 88/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 355902.5938 - mae: 385.5129 - val_loss: 323801.6250 - val_mae: 363.6207
Epoch 89/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 354916.5312 - mae: 384.5862 - val_loss: 330748.3438 - val_mae: 366.3119
Epoch 90/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 357580.5938 - mae: 384.5909 - val_loss: 328212.3750 - val_mae: 364.0677
Epoch 91/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 352328.5938 - mae: 382.9109 - val_loss: 323694.6875 - val_mae: 363.7391
Epoch 92/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 351011.7188 - mae: 382.3834 - val_loss: 327470.2500 - val_mae: 362.3632
Epoch 93/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 352288.0625 - mae: 382.4948 - val_loss: 326673.1562 - val_mae: 363.5610
Epoch 94/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 351682.7500 - mae: 381.8936 - val_loss: 323763.4688 - val_mae: 367.4194
Epoch 95/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 351724.2188 - mae: 382.3456 - val_loss: 323201.9688 - val_mae: 362.1493
Epoch 96/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 349877.4688 - mae: 380.5706 - val_loss: 322972.5312 - val_mae: 362.2786
Epoch 97/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 352271.7500 - mae: 383.0034 - val_loss: 323400.3750 - val_mae: 360.4019
Epoch 98/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 353263.6562 - mae: 381.6033 - val_loss: 325275.0312 - val_mae: 364.1347
Epoch 99/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 352248.8125 - mae: 382.9564 - val_loss: 316804.6562 - val_mae: 359.3388
Epoch 100/100
354/354 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 348066.8125 - mae: 380.2665 - val_loss: 328429.8125 - val_mae: 364.7340

In [ ]:
y_pred_emb = model_b_emb.predict([X_num_test_scaled, X_state_test, X_crop_test, X_season_test]).flatten()
rmse_emb = np.sqrt(mean_squared_error(y_test, y_pred_emb))
r2_emb = r2_score(y_test, y_pred_emb)
print("Test RMSE (embeddings):", rmse_emb)
print("Test R² (embeddings):", r2_emb)

In [ ]:
y_pred_emb = model_b_emb.predict([X_num_test_scaled, X_state_test, X_crop_test, X_season_test]).flatten()
rmse_emb = np.sqrt(mean_squared_error(y_test, y_pred_emb))
r2_emb = r2_score(y_test, y_pred_emb)
print("Test RMSE (embeddings):", rmse_emb)
print("Test R² (embeddings):", r2_emb)